# Generated by Django 3.1.1 on 2020-09-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemMapping',
            new_name='Order_item_mapping',
        ),
        migrations.RenameField(
            model_name='order_item_mapping',
            old_name='itemId',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='order_item_mapping',
            old_name='orderId',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='merchantId',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='storeId',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='merchantId',
            new_name='merchant',
        ),
    ]
