# Generated by Django 3.1.1 on 2020-09-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200928_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_item_mapping',
            new_name='OrderItemMapping',
        ),
    ]
